[project]
name = "human-avatar"
description = "Process photos of humans into animatable human avatars."
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amitmoryossef@gmail.com" },
]
readme = "README.md"
dependencies = [
    # Work with images
    "Pillow",
    # Pose estimation
    "pose-format",
    "mediapipe",
    # Transformers with vision
    "transformers",
    "torchvision",
    "scikit-image"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

server = [
    "Flask",
    "Werkzeug",
    "gunicorn",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "C90", # mccabe complexity
    "I", # isort
    "N", # pep8-naming
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "PT", # flake8-pytest-style
    "W605", # invalid escape sequence
    "BLE", # flake8-blind-except
]

[tool.setuptools]
packages = [
    "human_avatar"
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["human_avatar"]
